name: CMake (Linux + macOS, GCC and Clang)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        build_type: [Debug, Release]
        c_compiler: [gcc, clang]
        include:
          # Linux (GCC + Clang)
          - os: ubuntu-latest
            c_compiler: gcc
            cpp_compiler: g++
          - os: ubuntu-latest
            c_compiler: clang
            cpp_compiler: clang++
          # macOS (Clang only)
          - os: macos-latest
            c_compiler: clang
            cpp_compiler: clang++
        exclude:
          # Don’t try gcc on macOS (not preinstalled)
          - os: macos-latest
            c_compiler: gcc

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Set build dir
        id: vars
        run: echo "BUILD_DIR=${{ github.workspace }}/build-${{ matrix.os }}-${{ matrix.c_compiler }}-${{ matrix.build_type }}" >> $GITHUB_ENV

      - name: Configure CMake
        run: >
          cmake -B $BUILD_DIR
          -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
          -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
          -S ${{ github.workspace }}

      - name: Build
        run: cmake --build $BUILD_DIR --config ${{ matrix.build_type }}

      - name: Test
        working-directory: ${{ env.BUILD_DIR }}
        run: ctest --build-config ${{ matrix.build_type }}
